package ca.mcgill.ecse.cheecsemanager.features;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import java.sql.Date;
import java.util.List;
import java.util.Map;
import ca.mcgill.ecse.cheecsemanager.application.CheECSEManagerApplication;
import ca.mcgill.ecse.cheecsemanager.model.CheECSEManager;
import ca.mcgill.ecse.cheecsemanager.model.CheeseWheel.MaturationPeriod;
import ca.mcgill.ecse.cheecsemanager.model.Order;
import ca.mcgill.ecse.cheecsemanager.model.WholesaleCompany;
import ca.mcgill.ecse.cheecsemanager.controller.CheECSEManagerFeatureSet6Controller;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

public class DeleteWholesaleCompanyStepDefinitions {

  private CheECSEManager cheecsemanager = CheECSEManagerApplication.getCheecseManager();
  private String error = "";

  /**
   * Step definition that brings application into designated initial state. Uses the
   * model API generated by Umple
   * @author Santiago Padron (@santipadron)
   * @param dataTable , the Cucumber table presenting the companies we want to
   * exist in the system
   */
  @Given("the following wholesale company exists in the system \\(p16)")
  public void the_following_wholesale_company_exists_in_the_system_p16(
      io.cucumber.datatable.DataTable dataTable) {
    List<Map<String, String>> companies = dataTable.asMaps();

    for (Map<String, String> company : companies) {
      String name = company.get("name");
      String address = company.get("address");
      cheecsemanager.addCompany(name, address);
    }
  }

  /**
   * Step definition that brings application into designated intial state. Uses the
   * model API generated by Umple
   * @author Santiago Padron (@santipadron)
   * @param dataTable , the Cucumber table presenting the orders we want to
   * exist in the system
   */
  @Given("the following orders in the system \\(p16)")
  public void the_following_orders_in_the_system_p16(io.cucumber.datatable.DataTable dataTable) {
    List<Map<String, String>> orders = dataTable.asMaps();

    for (Map<String, String> order : orders) {
      // Parse the data table
      Date transactionDate = Date.valueOf(order.get("transactionDate"));
      int nrCheeseWheels = Integer.parseInt(order.get("nrCheeseWheels"));
      MaturationPeriod monthsAged = null;
      switch (order.get("monthsAged")) {                        // Convert string to the correct
        case "Six" : monthsAged = MaturationPeriod.Six;         // enum (we assume that it will be one of the
        case "Twelve" : monthsAged = MaturationPeriod.Twelve;   // four possible choices)
        case "TwentyFour" : monthsAged = MaturationPeriod.TwentyFour;
        case "ThirtySix" : monthsAged = MaturationPeriod.ThirtySix;
      }
      Date deliveryDate = Date.valueOf(order.get("deliveryDate"));
      String companyName = order.get("company");

      // Instantiate wanted orders in the system
      cheecsemanager.addTransaction(new Order(transactionDate, cheecsemanager, 
        nrCheeseWheels, monthsAged, deliveryDate, WholesaleCompany.getWithName(companyName)));
    }
  }

  /**
   * Step definition that calls the corresponding Controller method for deleting
   * a Wholesale Company from the system.
   * This step definition calls the {@link #callController(String) callController} method for updating the error message, if there is any
   * @author Santiago Padron (@santipadron)
   * @param companyName , the name of a Wholesale Company
   */
  @When("the facility manager attempts to delete the wholesale company with name {string} from the system \\(p16)")
  public void the_facility_manager_attempts_to_delete_the_wholesale_company_with_name_from_the_system_p16(
      String companyName) {
    callController(CheECSEManagerFeatureSet6Controller.deleteWholesaleCompany(companyName));
  }

  /**
   * Step definition that verifies that the right number of companies are in the system
   * @author Santiago Padron (@santipadron)
   * @param numOfCompanies , the expected number of companies in the system
   */
  @Then("the number of wholesale companies in the system shall be {int} \\(p16)")
  public void the_number_of_wholesale_companies_in_the_system_shall_be_p16(Integer numOfCompanies) {
    assertEquals(numOfCompanies, cheecsemanager.getCompanies().size());
  }

  /**
   * Step definition that verifies that the specified companies exist in the system
   * @author Santiago Padron (@santipadron)
   * @param dataTable , the specified companies we want to exist in the system
   */
  @Then("the following wholesale companies shall exist in the system \\(p16)")
  public void the_following_wholesale_companies_shall_exist_in_the_system_p16(
      io.cucumber.datatable.DataTable dataTable) {
    List<Map<String, String>> companies = dataTable.asMaps();

    for (Map<String, String> company : companies) {
      WholesaleCompany foundCompany = WholesaleCompany.getWithName(company.get("name"));

      assertNotNull(foundCompany, "The Company does not exist in the system.");
      assertEquals(company.get("address"), foundCompany.getAddress());
    }
  }

  /**
   * Step definition for checking that the correct error is raised
   * @author Santiago Padron (@santipadron)
   * @param errorName , the specified error string
   */
  @Then("the error {string} shall be raised \\(p16)")
  public void the_error_shall_be_raised_p16(String errorName) {
    assertTrue(error.contains(errorName), "The specified error was not raised.");
  }

  /**
   * Helper method used when calling the controller that sets the error message accordingly.
   * @author Santiago Padron (@santipadron)
   * @param result , the string returned by our controller feature methods
   */
  private void callController(String result) {
    if (!result.isEmpty()) {
      error = result;
    }
  }

}
