package ca.mcgill.ecse.cheecsemanager.features;

import java.util.List;
import java.util.Map;

import ca.mcgill.ecse.cheecsemanager.application.CheECSEManagerApplication;
import ca.mcgill.ecse.cheecsemanager.controller.*;
import ca.mcgill.ecse.cheecsemanager.model.*;

import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

import ca.mcgill.ecse.cheecsemanager.controller.CheECSEManagerFeatureSet7Controller;
import ca.mcgill.ecse.cheecsemanager.controller.CheECSEManagerFeatureSet3Controller;
import ca.mcgill.ecse.cheecsemanager.model.CheECSEManager;
import ca.mcgill.ecse.cheecsemanager.model.Farmer;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertFalse;

public class UpdateFarmerStepDefinitions {
  private CheECSEManager CheECSEManager = CheECSEManagerApplication.getCheecseManager();
  private String lastError = "";

  /**
   * Step definition that brings into existence farmers in the system. It uses the model API
   * generated by Umple.
   * 
   * @author Victoire Bergeron
   * @param dataTable List of farmers to add in the system
   */
  @Given("the following farmer exists in the system \\(p3)")
  public void the_following_farmer_exists_in_the_system_p3(
      io.cucumber.datatable.DataTable dataTable) {

    List<Map<String, String>> inputRows = dataTable.asMaps();

    for (var row : inputRows) {
      String email = row.get("email");
      String password = row.get("password");
      String name = row.get("name");
      String address = row.get("address");
      Farmer farmer =
          new Farmer(email, password, address, CheECSEManagerApplication.getCheecseManager());
      farmer.setName(name);
    }
  }

  /**
   * Step definition that attempts to update farmer in system. Calls controller method related to
   * updating farmer
   * 
   * @author Zirun Wang
   * @param email String containing the email of the farmer entered by the user
   * @param password String containing the password of the farmer entered by the user
   * @param address String containing the address of the farmer entered by the user
   * @param name String containing the name of the farmer entered by the user
   */
  @When("the facility manager attempts to update farmer {string} in the system with password {string}, address {string}, and name {string} \\(p3)")
  public void the_facility_manager_attempts_to_update_farmer_in_the_system_with_password_address_and_name_p3(
      String email, String password, String address, String name) {

    // Note the parameter order mapping to the controller:
    // updateFarmer(email, newPassword, newName, newAddress) — name and address are
    // swapped vs. the
    // Gherkin sentence.

    lastError = CheECSEManagerFeatureSet7Controller.updateFarmer(email, password, name, address);

  }

  /**
   * Step definition that verifies the number of farmers in the system. Uses the model API generated
   * by Umple
   * 
   * @author Wissam Abchiche
   * @param numberOfFarmers Integer containing the expected number of farmers
   */
  @Then("the number of farmers in the system shall be {int} \\(p3)")
  public void the_number_of_farmers_in_the_system_shall_be_p3(Integer numberOfFarmers) {
    assertEquals(numberOfFarmers, CheECSEManager.numberOfFarmers());
  }

  /**
   * Step definition that checks if a specific farmer exists in system with correct attributes. Uses
   * the model API generated by Umple
   * 
   * @author Maria Klinski
   * @param email String containing the expected email of the farmer
   * @param password String containing the expected password of the farmer
   * @param address String containing the expected address of the farmer
   * @param name String containing the expected name of the farmer
   */
  @Then("the farmer {string} with password {string}, address {string}, and name {string} shall exist in the system \\(p3)")
  public void the_farmer_with_password_address_and_name_shall_exist_in_the_system_p3(String email,
      String password, String address, String name) {

    User person = User.getWithEmail(email);
    assertNotNull(person, "The farmer with " + email + " does not exist in the system");
    assertTrue(person instanceof Farmer, "The person " + email + " is not a farmer");
    Farmer farmer = (Farmer) User.getWithEmail(email);
    assertEquals(password, farmer.getPassword());
    assertEquals(address, farmer.getAddress());
    assertEquals(name, farmer.getName());

  }

  /**
   * Step definition that makes sure that a specific farmer with certain attributes does not exist
   * in the system. Uses the model API generated by Umple
   * 
   * @author Sonia Ly
   * @param email String containing the email of the farmer
   * @param password String containing the password of the farmer
   * @param address String containing the address of the farmer
   * @param name String containing the name of the farmer
   */
  @Then("the farmer {string} with password {string}, address {string}, and name {string} shall not exist in the system \\(p3)")
  public void the_farmer_with_password_address_and_name_shall_not_exist_in_the_system_p3(
      String email, String password, String address, String name) {

    User u = User.getWithEmail(email);

    boolean exists =
        (u != null) && (u instanceof Farmer) && password.equals(((Farmer) u).getPassword())
            && address.equals(((Farmer) u).getAddress()) && name.equals(((Farmer) u).getName());

    assertFalse(exists, "The farmer with " + email + ", " + password + ", " + address + ", " + name
        + " exists in the system");
  }

  /**
   * Step definition that checks if the farmers exist in the system. Uses the model API generated by
   * Umple
   * 
   * @author Emily Sun
   * @param dataTable List of expected farmers in the system
   */
  @Then("the following farmers shall exist in the system \\(p3)")
  public void the_following_farmers_shall_exist_in_the_system_p3(
      io.cucumber.datatable.DataTable dataTable) {

    List<Map<String, String>> expectedFarmers = dataTable.asMaps();

    for (Map<String, String> expectedFarmer : expectedFarmers) {
      String email = expectedFarmer.get("email");
      User person = User.getWithEmail(email);
      assertNotNull(person, "The farmer with " + email + " does not exist in the system");
      assertTrue(person instanceof Farmer, "The person " + email + " is not a farmer");
      Farmer actualFarmer = (Farmer) User.getWithEmail(email);
      assertEquals(expectedFarmer.get("name"), actualFarmer.getName());
      assertEquals(expectedFarmer.get("address"), actualFarmer.getAddress());
      assertEquals(expectedFarmer.get("password"), actualFarmer.getPassword());
    }
  }

  /**
   * Step definition that checks if a correct error was raised. Uses the model API generated by
   * Umple
   * 
   * @author Yani Zhang
   * @param expectedError String containing the expected error
   */
  @Then("the error {string} shall be raised \\(p3)")
  public void the_error_shall_be_raised_p3(String expectedError) {
    assertEquals(expectedError, lastError);
  }
}
