package ca.mcgill.ecse.cheecsemanager.fxml.controller.cheesewheel;

import ca.mcgill.ecse.cheecsemanager.application.ApplicationNavigator;
import ca.mcgill.ecse.cheecsemanager.controller.CheECSEManagerFeatureSet3Controller;
import ca.mcgill.ecse.cheecsemanager.controller.TOCheeseWheel;
import ca.mcgill.ecse.cheecsemanager.fxml.layout.ToastFactory;
import ca.mcgill.ecse.cheecsemanager.fxml.state.NavigationState;
import ca.mcgill.ecse.cheecsemanager.fxml.state.PageType;
import ca.mcgill.ecse.cheecsemanager.fxml.state.TOForm;
import ca.mcgill.ecse.cheecsemanager.fxml.util.FormHelper;
import ca.mcgill.ecse.cheecsemanager.fxml.util.InvalidInputException;
import ca.mcgill.ecse.cheecsemanager.fxml.util.PageSwitchEvent;
import ca.mcgill.ecse.cheecsemanager.model.CheeseWheel.MaturationPeriod;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.*;
import javafx.scene.text.Text;
import java.net.URL;
import java.util.ResourceBundle;

public class CheeseWheelFormController implements Initializable {

  @FXML
  private Label labelId;
  @FXML
  private TextField inputFieldId;
  @FXML
  private Label labelMonthsAged;
  @FXML
  private ChoiceBox<MaturationPeriod> choiceBoxMonthsAged;
  @FXML
  private Label labelIsSpoiled;
  @FXML
  private CheckBox checkBoxIsSpoiled;

  @FXML
  private Button buttonCancel;
  @FXML
  private Button buttonSave;

  @FXML
  private Text textError;

  private TOCheeseWheel currentCheeseWheel;


  @Override
  public void initialize(URL url, ResourceBundle resourceBundle) {

    // Initialize Label text with formatting
    labelId.setText(FormHelper.convertCamelCaseToWords("id"));
    // Disable Autounique keys as they are autogenerated
    inputFieldId.setDisable(true);
    inputFieldId.setText("Autogenerated");
    // Initialize Label text with formatting
    labelMonthsAged.setText(FormHelper.convertCamelCaseToWords("monthsAged"));
    // Initialize enum dropdown
    choiceBoxMonthsAged.getItems().addAll(MaturationPeriod.values());
    // Initialize Label text with formatting
    labelIsSpoiled.setText(FormHelper.convertCamelCaseToWords("isSpoiled"));
  }

  public void setData(TOForm<?, TOCheeseWheel> toForm) {
    if (toForm.getPageType().equals(PageType.UPDATE)) {
      handleUpdateInit(toForm.getData());
    }
  }


  public void handleUpdateInit(TOCheeseWheel cheeseWheel) {
    this.currentCheeseWheel = cheeseWheel;

    inputFieldId.setText(String.valueOf(cheeseWheel.getId()));
    if (cheeseWheel.getMonthsAged() != null)
      choiceBoxMonthsAged.setValue(MaturationPeriod.valueOf(cheeseWheel.getMonthsAged()));
    checkBoxIsSpoiled.setSelected(cheeseWheel.getIsSpoiled());

    // Mark Key field as Disabled
    inputFieldId.setDisable(true);

    System.out.println("Preloaded CheeseWheel data");
  }

  @FXML
  private void onSave(ActionEvent event) {
    try {
      // Assign Default value for Autounique key as its not in use
      Integer id = Integer.valueOf(inputFieldId.getText());
      MaturationPeriod monthsAged = choiceBoxMonthsAged.getValue();
      boolean isSpoiled = checkBoxIsSpoiled.isSelected();
      String savedStatus = "";
      // Perform Update Operation
      if (currentCheeseWheel != null) {
        savedStatus = CheECSEManagerFeatureSet3Controller.updateCheeseWheel(id,
            monthsAged.toString(), isSpoiled);

      }
      currentCheeseWheel =
          CheECSEManagerFeatureSet3Controller.getCheeseWheel(currentCheeseWheel.getId());

      // Validate Controller response
      if (!savedStatus.isEmpty() && !savedStatus.equals("Cheese wheel updated successfully."))
        throw new InvalidInputException(savedStatus);
      else {
        textError.setText("");
        buttonSave.setDisable(true);
        ToastFactory.createSuccess(buttonSave,
            "Successfully saved item. Redirecting back to table...");
        FormHelper.triggerAfterDelay(() -> {

          ApplicationNavigator.getInstance().updatePages("CheeseWheel");

          NavigationState<TOForm<?, TOCheeseWheel>> navState =
              new NavigationState<>(null, PageType.BACK, null);
          navState.setData(new TOForm<>(currentCheeseWheel, PageType.UPDATE));

          ApplicationNavigator.getInstance().switchPage("CheeseWheel",
              new PageSwitchEvent(navState));

          NavigationState<TOForm<?, TOCheeseWheel>> updateState = new NavigationState<>(null,
              PageType.UPDATE, "view/page/cheesewheel/CheeseWheelDisplayOne.fxml");
          updateState.setData(new TOForm<>(currentCheeseWheel, PageType.UPDATE));

          ApplicationNavigator.getInstance().switchPage("CheeseWheel",
              new PageSwitchEvent(updateState));

        }, 2);
      }

    } catch (RuntimeException e) {
      textError.setText(FormHelper.formatTextMessage(e));
    }
  }

  public void onCancel(ActionEvent actionEvent) {
    ApplicationNavigator.getInstance().switchPage("CheeseWheel",
        new PageSwitchEvent(new NavigationState<>(null, PageType.BACK, null)));
  }
}
